### ISSUE TITLE
Thanks! Neko runtime error

### ISSUE THREAD

**Issue by cambiata** [shohei909/haxe_stb_ogg_sound#1]
Happy to find this! Great work!

Runtime error on Neko (Invalid operation (-) thrown from Header.hx line 61) - but I guess that you are aware of that.

Do we dare to hope for an ogg encoder also..? :-)

/ Jonas

**Comment by shohei909** [comment]
Thanks for report !

This bug is fixed in 0.0.1 release (I failed to push it). Please reinstall from haxelib.

I'm afraid, but I will not write an encoder. Because [stb_vorbis](https://github.com/nothings/stb) has no encoder, so it is too hard.

**Comment by cambiata** [comment]
Ah, I just compiled using the run-neko.hxml, and I didn't realize that it doesn't use the haxelib version, it just refers to -cp src...

What about cpp target?
