### ISSUE TITLE
Small OGG files failed to decode

### ISSUE THREAD

**Issue by ncannasse** [shohei909/haxe_stb_ogg_sound#2]
Hi,

I have some issue with the library when decoding some small sound file. (maybe because it has only one frame of data ?)

He's the file link : http://ncannasse.fr/file/R_sound_fx_wav.ogg
It's been encoded using `oggenc2` commandline utility with this WAV source : 
https://raw.githubusercontent.com/ncannasse/heaps/master/samples/sound/res/sound_fx.wav

Thank you for the library, I'm looking forward having it working in my Heaps framework.

**Comment by shohei909** [comment]
Thanks for report. I fixed it, and released version 0.0.2.
